name: reusable workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        description: the name of the deployable artifact files
        required: false
        default: dist
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying....
        run: echo "deploying script hehe"
      - name: get code
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifcat-name}}
      - name: list files
        run: ls
###check reusable workfow data
